### ISSUE TITLE
Props when quiet mode is set.

### ISSUE THREAD

**Issue by LeonaMorro** [nPoseTeam/nPose-Prop-Plugin#4]
See: https://github.com/nPoseTeam/nPose-V4/issues/4

**Comment by HowardBaxton** [comment]
I tested this new PROP plugin and happy to report that while a prop is in quiet mode now, it does not report new position when moved but PosDump does.  This new update also reports the accurate and up to date prop position/rotation as expected.

I will close this issue now.
